name: Go Tests
env:
  GOPRIVATE: "github.com/govnet-mofa"
on: 
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: '1.21.0'
      gomod_token:
        required: false
        type: string
        default: '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'
    # secrets: 
      git-token:
        type: string
        required: false
        default: 'dckr_pat_TLq0t2oN4tqcYXtMXghD_sozOog'
      git-user:
        type: string
        required: false
        default: 'ronaldkasagga'
jobs:
  go-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        token: ${{ inputs.gomod_token }}
        go-version: ${{ inputs.version }}
        cache: true
    - name: Configure Host SSH
      uses: shimataro/ssh-key-action@v2
      with:
        name: ifas_github
        key: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
          QyNTUxOQAAACCxhDsc4Jetw6+ZRU3e8kTBAOUcDJD0C0wgLkFrQ+m3sAAAAJgVMHDkFTBw
          5AAAAAtzc2gtZWQyNTUxOQAAACCxhDsc4Jetw6+ZRU3e8kTBAOUcDJD0C0wgLkFrQ+m3sA
          AAAEC1X81ZVM+fkLipdlmaz5JO7PX8NEqDt+xFQLPG11aH3LGEOxzgl63Dr5lFTd7yRMEA
          5RwMkPQLTCAuQWtD6bewAAAAFWdpdGh1YkBtb2ZhLmdvdm5ldC51Zw==
          -----END OPENSSH PRIVATE KEY-----    
    - name: Configure git for private modules
      run: git config --global url."https://${{ secrets.gomod-token }}@github.com/".insteadOf "https://github.com/"
    - name: Download dependencies
      run: go mod download
    - name: Run tests
      run: go test ./...