name: Go Tests
env:
  GOPRIVATE: "github.com/govnet-africa"
on: 
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: '1.22.0'
    secrets: 
      gomod-token:
        required: true
      git-user:
        required: true
jobs:
  go-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        token: ${{ secrets.gomod-token }}
        go-version: ${{ inputs.version }}
        cache: true
    - name: Configure Netrc
      uses: extractions/netrc@v2
      with:
        machine: github.com
        username: ${{ secrets.git-user }}
        password: ${{ secrets.gomod-token }}    
    - name: Download dependencies
      run: go mod download
    - name: Run tests
      run: go test ./...