name: Go Tests
env:
  GOPRIVATE: "github.com/govnet-mofa"
on: 
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: '1.21.0'
      gomod_token:
        required: false
        type: string
        default: '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'
    # secrets: 
      git-token:
        type: string
        required: false
        default: 'dckr_pat_TLq0t2oN4tqcYXtMXghD_sozOog'
      git-user:
        type: string
        required: false
        default: 'ronaldkasagga'
jobs:
  go-test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        token: ${{ inputs.gomod_token }}
        go-version: ${{ inputs.version }}
        cache: true
    - name: Configure git for private modules
      run: git config --global url."https://${{ secrets.gomod-token }}@github.com".insteadOf "https://github.com"
    - name: Download dependencies
      run: go mod download
    - name: Run tests
      run: go test ./...