name: Go Deploy

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      service:
        required: true
        type: string
      service-port:
        required: false
        type: number
      deploy-host-ip:
        required: true
        type: string
      deploy-host-port:
        required: true
        type: number
      deploy-dir:
        required: true
        type: string
      go-version:
        required: false
        type: string
    secrets:
      gomod-token:
        required: true
      git-user:
        required: true
      deploy-ssh-private-key:
        required: true  
jobs:
  build:
    uses: govnet-africa/devops/.github/workflows/go-build.yaml@v3
    with:
      service: ${{ inputs.service }}
      version: ${{ inputs.version }}
      service-port: ${{ inputs.service-port || 80 }}
      go-version: ${{ inputs.go-version || '1.22' }}
    secrets:  
      gomod-token: ${{ secrets.gomod-token }}
      git-user: ${{ secrets.git-user }}
    permissions:
      id-token: write
      contents: read
  deploy:
    needs: build
    uses: govnet-africa/devops/.github/workflows/vps-docker-deploy.yaml@v3
    with:
      service: ${{ inputs.service }}
      deploy-host: "${{ inputs.service }}.govnet"
      deploy-host-ip: ${{ inputs.deploy-host-ip }}
      deploy-host-port: ${{ inputs.deploy-host-port }}
      deploy-dir: ${{ inputs.deploy-dir }}
      tag: ${{ inputs.version || github.sha }}
    secrets:
       deploy-ssh-private-key: ${{ secrets.deploy-ssh-private-key }}
    permissions:
      id-token: write
      contents: read
    