name: Go Deploy

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      service:
        required: true
        type: string
      service-port:
        required: false
        type: number
      go-version:
        required: false
        type: string
      dockerhub-org:
        required: false
        type: string
      gomod-token:
        required: false
        type: string
      git-user:
        type: string
        required: false
jobs:
  build:
    uses: govnet-mofa/ifas-devops/.github/workflows/go-build.yaml@go1
    with:
      service: ${{ inputs.service }}
      version: ${{ inputs.version }}
      service-port: ${{ inputs.service-port || 80 }}
      go-version: ${{ inputs.go-version || '1.21' }}
      dockerhub-org: ${{ inputs.dockerhub-org || 'govnetservices' }}
      gomod-token: ${{ inputs.gomod-token || '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' }}
      git-user: ${{ inputs.git-user || 'ronaldkasagga' }}
    permissions:
      id-token: write
      contents: read
  # publish:
  #   needs: build
  #   uses: govnet-mofa/ifas-devops/.github/workflows/ecr-publish.yaml@main
  #   with:
  #     ecr-name: ${{ inputs.service }}
  #     environment: ${{ inputs.environment }}
  #     artifact-key:  ${{ inputs.service }}-${{ inputs.environment }}-build
  #     ecr-tag: ${{ inputs.version }}
  #   permissions:
  #     id-token: write
  #     contents: read
  # deploy:
  #   needs: publish
  #   uses: govnet-mofa/ifas-devops/.github/workflows/ec2-docker-deploy.yaml@main
  #   with:
  #     service: ${{ inputs.service }}
  #     service-dockercompose-image: ${{ inputs.service-dockercompose-image }}
  #     service-dockercompose-name: ${{ inputs.service-dockercompose-name }}
  #     dockercompose-cmd: ${{ inputs.dockercompose-cmd }}
  #     tag: ${{ inputs.version }}
  #     environment: ${{ inputs.environment }}
  #   permissions:
  #     id-token: write
  #     contents: read
    