name: Java Deploy

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: null
      java-version:
        required: false
        type: string
        default: '20'
      java-distribution:
        required: false
        type: string
        default: 'temurin'
      jre-cache:
        required: false
        type: string
        default: 'maven'
      service:
        required: true
        type: string
      service-port:
        required: false
        type: number
        default: 8080
      spring-profile:
        required: false
        type: string
        default: 'staging'
      dockerfile-runner-img:
        required: false
        type: string
        default: 'eclipse-temurin:${{ inputs.java-version }}-jre'
      
jobs:
  build:
    uses: govnet-obrs/devops/.github/workflows/java-build.yaml@v2.3
    with:
      service: ${{ inputs.service }}
      service-port: ${{ inputs.service-port }}
      version:  ${{inputs.version }}
      java-version: ${{ inputs.java-version }}
      java-distribution: ${{ inputs.java-distribution }}
      jre-cache: ${{ inputs.jre-cache }}
      dockerfile-runner-img: ${{ inputs.dockerfile-runner-img }}
    permissions:
      id-token: write
      contents: read
  staging:
    needs: build
    if: github.ref == 'refs/head/staging'
    uses: govnet-obrs/devops/.github/workflows/vps-docker-deploy.yaml@v2.3
    with:
      service: ${{ inputs.service }}
      tag: ${{ inputs.version || github.sha }}
    permissions:
      id-token: write
      contents: read
  recovery:
    needs: build
    if: github.ref == 'refs/head/recovery'
    uses: govnet-obrs/devops/.github/workflows/ts-docker-deploy.yaml@v2.3
    with:
      service: ${{ inputs.service }}
      tag: ${{ inputs.version || github.sha }}
    permissions:
      id-token: write
      contents: read
  prod:
    needs: build
    if: github.ref == 'refs/head/production'
    uses: govnet-obrs/devops/.github/workflows/ts-docker-deploy.yaml@v2.3
    with:
      service: ${{ inputs.service }}
      tag: ${{ inputs.version || github.sha }}
    permissions:
      id-token: write
      contents: read
    