env:
  DOCKER_BUILDER_IMG: eclipse-temurin:17-jdk-alpine
  DOCKER_RUNNER_IMG: paketobuildpacks/graalvm:latest
  DOCKERHUB_REPO: govnetservices/${{github.repository}}
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: null
      java-version:
        required: false
        type: string
        default: '17'
      java-distribution:
        required: false
        type: string
        default: 'temurin'
      jre-cache:
        required: false
        type: string
        default: 'maven'
      service:
        required: true
        type: string
      service-port:
        required: false
        type: number
        default: 8080
jobs:
  java-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Setup JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: ${{ inputs.jre-cache }}
    - name: Build with ${{ inputs.jre-cache }}
      run: mvn -B package --file pom.xml -DskipTests
    - name: Set env
      run: |
        echo "GITHUB_SHA_SHORT=`git rev-parse --short ${{ github.sha }}`" >> $GITHUB_ENV
        echo "GITHUB_BRANCH_SHORT=`git branch --show-current | sed 's/\//_/g' | tr -d ' '`" >> $GITHUB_ENV
        echo "DOCKERHUB_REPO=govnetservices/$(echo ${{ env.GITHUB_REPOSITORY }} | cut -d '/' -f 2')" >> $GITHUB_ENV
    - name: Write Dockerfile
      run: |
        cat <<EOF > Dockerfile 
        FROM ${{env.DOCKER_BUILDER_IMG}} AS build
        WORKDIR /workspace/app
        COPY mvnw .
        COPY .mvn .mvn
        COPY pom.xml .
        COPY src src
        RUN ./mvnw install -DskipTests
        RUN mkdir -p target/dependency && (cd target/dependency; jar -xf ../*.jar)
        RUN mkdir -p target/extracted && java -Djarmode=layertools -jar target/*.jar extract --destination target/extracted
        FROM ${{env.DOCKER_RUNNER_IMG}}
        VOLUME /tmp
        ARG EXTRACTED=/workspace/app/target/extracted
        COPY --from=build ${EXTRACTED}/dependencies/ ./
        COPY --from=build ${EXTRACTED}/spring-boot-loader/ ./
        COPY --from=build ${EXTRACTED}/snapshot-dependencies/ ./
        COPY --from=build ${EXTRACTED}/application/ ./
        ENV APP_PORT=${{ inputs.service-port }}
        ENV VERSION=${{ inputs.service }}-${{ inputs.version || env.GITHUB_SHA_SHORT }}
        EXPOSE ${{ inputs.service-port }}
        ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
        EOF
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: govnetservices
        password: 'dckr_pat_TLq0t2oN4tqcYXtMXghD_sozOog'
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKERHUB_REPO }}:${{ github.sha }}
          ${{ env.DOCKERHUB_REPO }}:${{ env.GITHUB_BRANCH_SHORT }}
          ${{ env.DOCKERHUB_REPO }}:${{ inputs.version || env.GITHUB_SHA_SHORT }}
          ${{ env.DOCKERHUB_REPO }}:latest