name: Java Deploy

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: null
      java-version:
        required: false
        type: string
        default: '17'
      java-distribution:
        required: false
        type: string
        default: 'temurin'
      jre-cache:
        required: false
        type: string
        default: 'maven'
      service:
        required: true
        type: string
      service-port:
        required: false
        type: number
        default: 8080
      mvn-user:
        required: false
        type: string
      mvn-token:
        required: false
        type: string
jobs:
  build:
    uses: govnet-mofa/ifas-devops/.github/workflows/java-build.yaml@devops
    with:
      service: ${{ inputs.service }}
      service-port: ${{ inputs.service-port }}
      version:  ${{inputs.version }}
      java-version: ${{ inputs.java-version }}
      java-distribution: ${{ inputs.java-distribution }}
      jre-cache: ${{ inputs.jre-cache }}
      mvn-user: ${{ inputs.mvn-user }}
      mvn-token: ${{ inputs.mvn-token }}
    permissions:
      id-token: write
      contents: read
  deploy:
    needs: build
    uses: govnet-mofa/ifas-devops/.github/workflows/vps-docker-deploy.yaml@devops
    with:
      service: ${{ inputs.service }}
      tag: ${{ inputs.version || github.sha }}
    permissions:
      id-token: write
      contents: read
    