env:
  DOCKER_BUILDER_IMG: openjdk:17-oraclelinux8
  DOCKER_RUNNER_IMG: bitnami/minideb:latest
  DOCKERHUB_REPO: govnetservices/${{github.repository}}
  DOCKER_BUILDKIT: 1
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: null
      java-version:
        required: false
        type: string
        default: '17'
      java-distribution:
        required: false
        type: string
        default: 'temurin'
      jre-cache:
        required: false
        type: string
        default: 'maven'
      service:
        required: true
        type: string
      service-port:
        required: false
        type: number
        default: 8080
jobs:
  java-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: |
        echo "GITHUB_SHA_SHORT=`git rev-parse --short ${{ github.sha }}`" >> $GITHUB_ENV
        echo "GITHUB_BRANCH_SHORT=`git branch --show-current | sed 's/\//_/g' | tr -d ' '`" >> $GITHUB_ENV
        echo "DOCKERHUB_REPO=govnetservices/$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: govnetservices
        password: 'dckr_pat_TLq0t2oN4tqcYXtMXghD_sozOog'
    - name: Setup JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: ${{ inputs.jre-cache }}
    - name: Build with ${{ inputs.jre-cache }}
      run: |
        rm -rf target && \
        mvn -B package --file pom.xml -DskipTests && \
        mkdir -p target/{dependency,extracted} && \
        (cd target/dependency; jar -xf ../*.jar) && \
        java -Djarmode=layertools -jar target/*.jar extract --destination target/extracted 
    - name: Write Dockerfile
      run: |
        cat <<EOF > Dockerfile 
        FROM openjdk:17-oraclelinux8 as builder
        USER root
        RUN jlink \
          --module-path "$JAVA_HOME/jmods" \
          --add-modules java.compiler,java.sql,java.naming,java.management,java.instrument,java.rmi,java.desktop,jdk.internal.vm.compiler.management,java.xml.crypto,java.scripting,java.security.jgss,jdk.httpserver,java.net.http,jdk.naming.dns,jdk.crypto.cryptoki,jdk.unsupported \
          --verbose \
          --strip-debug \
          --compress 2 \
          --no-header-files \
          --no-man-pages \
          --output /opt/jre-minimal
        USER app
        WORKDIR /app
        COPY target target
        FROM ${{env.DOCKER_RUNNER_IMG}}
        VOLUME /tmp
        COPY --from=builder /app/target/extracted/dependencies/ ./
        COPY --from=builder /app/target/extracted/spring-boot-loader/ ./
        COPY --from=builder /app/target/extracted/snapshot-dependencies/ ./
        COPY --from=builder /app/target/extracted/application/ ./
        COPY --from=builder /opt/jre-minimal /opt/jre0
        ENV JAVA_HOME=/opt/jre0
        ENV PATH="$PATH:$JAVA_HOME/bin"
        ENV APP_PORT=${{ inputs.service-port }}
        ENV VERSION=${{ inputs.service }}-${{ inputs.version || env.GITHUB_SHA_SHORT }}
        EXPOSE ${{ inputs.service-port }}
        ENTRYPOINT ["/opt/jre0/bin/java", "org.springframework.boot.loader.JarLauncher"]
        EOF
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKERHUB_REPO }}:${{ env.GITHUB_BRANCH_SHORT }}
          ${{ env.DOCKERHUB_REPO }}:${{ inputs.version || env.GITHUB_SHA_SHORT }}
          ${{ env.DOCKERHUB_REPO }}:latest