env:
  DOCKERFILE_BUILDER_IMG: eclipse-temurin:${{ inputs.java-version }}-jdk
  DOCKERHUB_REPO: ${{ inputs.dockerhub-org }}/${{ github.repository }}
  DOCKER_BUILDKIT: 1
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        default: null
      java-version:
        required: false
        type: string
        default: '20'
      java-distribution:
        required: false
        type: string
        default: 'temurin'
      jre-cache:
        required: false
        type: string
        default: 'maven'
      mvn-user:
        required: true
        type: string
      mvn-token:
        required: true
        type: string
      service:
        required: true
        type: string
      service-port:
        required: false
        type: number
        default: 8080
      dockerhub-org:
        required: false
        type: string
        default: 'govnetservices'
      dockerfile-runner-img:
        required: false
        type: string
        default: 'alpine:latest'
      consul-host:
        required: true
        type: string
      consul-port:
        required: true
        type: number
jobs:
  java-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: |
        echo "GITHUB_SHA_SHORT=`git rev-parse --short ${{ github.sha }}`" >> $GITHUB_ENV
        echo "GITHUB_BRANCH_SHORT=`git branch --show-current | sed 's/\//_/g' | tr -d ' '`" >> $GITHUB_ENV
        echo "DOCKERHUB_REPO=${{ inputs.dockerhub-org }}/$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_ENV
        echo "SERVICE_BUILD=`date -I`-`git rev-parse --short ${{ github.sha }}`" >> $GITHUB_ENV
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: govnetservices
        password: 'dckr_pat_TLq0t2oN4tqcYXtMXghD_sozOog'
    - name: Setup JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: ${{ inputs.jre-cache }}
    - name: Set up Maven settings.xml
      run: |
        cat <<EOF > ~/.m2/settings.xml 
        <?xml version="1.0" encoding="UTF-8"?>
        <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <activeProfiles>
              <activeProfile>github</activeProfile>
          </activeProfiles>
          <profiles>
              <profile>
                <id>github</id>
                <repositories>
                    <repository>
                      <id>central</id>
                      <url>https://repo1.maven.org/maven2</url>
                    </repository>
                    <repository>
                      <id>github</id>
                      <url>https://maven.pkg.github.com/govnet-mofa/ifas</url>
                      <snapshots>
                          <enabled>true</enabled>
                      </snapshots>
                    </repository>
                </repositories>
              </profile>
          </profiles>

          <servers>
              <server>
                <id>github</id>
                <username>${{ inputs.mvn-user }}</username>
                <password>${{ inputs.mvn-token }}</password>
              </server>
          </servers>
        </settings>
        EOF
    - name: Build with ${{ inputs.jre-cache }}
      run: |
        rm -rf target && \
        mvn -B package --file pom.xml -DskipTests && \
        mkdir -p target/{dependency,extracted} && \
        (cd target/dependency; jar -xf ../*.jar) && \
        java -Djarmode=layertools -jar target/*.jar extract --destination target/extracted 
    - name: Write Dockerfile
      env:
        JRE_HOME: /opt/jre
      run: |
        cat <<EOF > Dockerfile 
        FROM ${{ env.DOCKERFILE_BUILDER_IMG }} as builder
        USER root
        RUN jlink \
          --module-path "$JAVA_HOME/jmods" \
          --add-modules java.compiler,java.sql,java.naming,java.management,java.instrument,java.rmi,java.desktop,jdk.internal.vm.compiler.management,java.xml.crypto,java.scripting,java.security.jgss,jdk.httpserver,java.net.http,jdk.naming.dns,jdk.crypto.cryptoki,jdk.unsupported \
          --verbose \
          --strip-debug \
          --compress 2 \
          --no-header-files \
          --no-man-pages \
          --output /opt/jre-minimal
        USER app
        WORKDIR /app
        COPY target target
        FROM ${{ inputs.dockerfile-runner-img }}
        VOLUME /tmp
        COPY --from=builder /app/target/extracted/dependencies/ ./
        COPY --from=builder /app/target/extracted/spring-boot-loader/ ./
        COPY --from=builder /app/target/extracted/snapshot-dependencies/ ./
        COPY --from=builder /app/target/extracted/application/ ./
        COPY --from=builder /opt/jre-minimal ${{ env.JRE_HOME }}
        ENV JAVA_HOME=${{ env.JRE_HOME }}
        ENV PATH="$PATH:$JAVA_HOME/bin"
        ENV APP_PORT=${{ inputs.service-port }}
        ENV BUILD=${{ env.SERVICE_BUILD }}
        ENV VERSION=${{ inputs.service }}-${{ inputs.version || env.GITHUB_SHA_SHORT }}
        EXPOSE ${{ inputs.service-port }}
        RUN root:x:0:0:root:/root:/bin/bash => root:x:0:0:root:/root:/sbin/nologin
        ENTRYPOINT ["${{ env.JRE_HOME }}/bin/java", "-Dspring.cloud.consul.host=${{ inputs.consul-host }}", "-Dspring.cloud.consul.port=${{ inputs.consul-port }}", "org.springframework.boot.loader.JarLauncher"]
        EOF
    - name: Set docker branch tag
      run: |
        echo "GITHUB_BRANCH_SHORT=`git branch --show-current | sed 's/\//_/g' | tr -d ' '`" >> $GITHUB_ENV
    - name: Build and push docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ env.DOCKERHUB_REPO }}:${{ github.sha }}
          ${{ env.DOCKERHUB_REPO }}:${{ inputs.version || env.GITHUB_SHA_SHORT }}
          ${{ env.DOCKERHUB_REPO }}:latest