name: Deploy to docker host
  
on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: ${{ github.sha }}
      deploy-host-ip:
        required: false
        type: string
        default: 172.232.194.72
      deploy-host-port:
        required: false
        type: number
        default: 57244
      deploy-user:
        required: false
        type: string
        default: 'github-actions'
      deploy-dir:
        required: false
        type: string
        default: '/deploy/obrs-be'
jobs:
  docker_deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    env:
      DEPLOY_HOST: "${{ inputs.service }}.govnet"
    steps:
      - name: Configure Host SSH
        uses: shimataro/ssh-key-action@v2
        with:
          name: govdev_github
          known_hosts: change-me
          config: |
            Host ${{ env.DEPLOY_HOST }}
              Port ${{ inputs.deploy-host-port }}
              HostName ${{ inputs.deploy-host-ip }}
              User ${{ inputs.deploy-user }}
              IdentityFile ~/.ssh/govdev_github
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACBCsCnzNzBMP4YbWHaKr3/RFqvWrfsJpY9MrbUrLMqvGAAAAKCOowF8jqMB
            fAAAAAtzc2gtZWQyNTUxOQAAACBCsCnzNzBMP4YbWHaKr3/RFqvWrfsJpY9MrbUrLMqvGA
            AAAEDChozEnz6zmgQJTNUCuf70AkQwMFNNvS+IAkGQpGOXuEKwKfM3MEw/hhtYdoqvf9EW
            q9at+wmlj0yttSssyq8YAAAAGWFjdGlvbnNAc3RhZ2Uub2Jycy5nb3ZuZXQBAgME
            -----END OPENSSH PRIVATE KEY-----
      - name: Overwrite known hosts of ${{ env.DEPLOY_HOST }}
        run: ssh-keyscan ${{ inputs.deploy-host-ip }} > ~/.ssh/known_hosts
      - name: Deploy ${{ inputs.service }} with docker
        run: ssh ${{ env.DEPLOY_HOST }} "make -C  ${{ inputs.deploy-dir }} deploy-service-tag service=${{ inputs.service }} tag=${{ inputs.tag }}"