name: Deploy to docker host
  
on: 
  workflow_dispatch:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: ${{ github.sha }}
jobs:
  docker_deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
      - name: Configure Host SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_HOST_PRIVATE_KEY }}
          name: ifas_dev
          known_hosts: ${{ secrets.DEPLOY_HOST_FINGERPRINT }}
          config: |
            Host github.com
              HostName github.com
              User ${{ secrets.DEPLOY_USER }}
              IdentityFile ~/.ssh/ifas_dev
      - name: Deploy ${{ inputs.service }}
        env:
          SSH_USER_HOST: ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}
        run: ssh ${{ secrets.DEPLOY_HOST }} "make -C  ${{ secrets.DOCKERCOMPOSE_DIR }} deploy-service-tag service=${{ inputs.service }} tag=${{ inputs.tag }}"